### ISSUE TITLE
check energy timestep_init and run phases needs to set error variables.

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/atmospheric_physics#159]
Currently the `check_energy_chng` subroutines in the `check_energy` schemes here:

https://github.com/ESCOMP/atmospheric_physics/blob/main/schemes/check_energy/check_energy_chng.F90#L30

and here:

https://github.com/ESCOMP/atmospheric_physics/blob/main/schemes/check_energy/check_energy_chng.F90#L177

have `errmsg` and `errflg` variables that are `intent(out)`, but which are not actually set to anything.  This could potentially cause model crashes depending on the compiler configuration and error-checking method, so to be safe it would be good to at least set them to their default values, e.g.:

```
errflg = 0
errmsg = ''
```

I believe this change won't currently impact anything (it is more of a precaution), and thus could be brought in with any upcoming atmospheric_physics PR.

**Comment by jimmielin** [comment]
Thanks @nusbaume! I will fill the `errflg` and `errmsg` in the `check_energy` related subroutines. I missed some of these in the other schemes as well so I will fill throughout with the error message/flag arguments for the check_energy related schemes.

**Comment by jimmielin** [comment]
Fixed in #160!
