### ISSUE TITLE
Change "radians" units to "rad"

### ISSUE THREAD

**Issue by peverwhee** [ESCOMP/atmospheric_physics#172]
To keep with the use of SI units in the CCPP, update references to "radians" to "rad" in:

schemes/held_suarez/held_suarez_1994.meta
schemes/tj2016/tj2016_sfc_pbl_hs.meta
schemes/tropopause_find/tropopause_find.meta

**Comment by jimmielin** [comment]
Hi @peverwhee I think this could be closed now? It looks like your commit (e7a599f) has changed the `radians` to `rad` in the files you mentioned. I tested that the schemes build / run correctly as well so it should be updated in both CAM-SIMA and atmos_phys ends now. Thanks!

**Comment by peverwhee** [comment]
good call @jimmielin
