### ISSUE TITLE
Kessler suite uses two versions of rair

### ISSUE THREAD

**Issue by gold2718** [ESCOMP/atmospheric_physics#22]
Kessler physics requires the gas constant for dry air in order to compute the inverse of `kappa`. However, the `geopotential_t` function uses the height-dependent version of this quantity.

While this is unlikely to cause any problem for reasonable Kessler physics simulations (Kessler physics does not make much sense above altitudes where `rair` is likely to vary), is this a suite usage that should be cleaned up? 

At least CAMDEN / CCPP Framework generated the correct code for this situation!

**Comment by nusbaume** [comment]
Both `kessler` and `geopotential_temp` now use `composition_dependent_gas_constant_of_dry_air` for rair, which resolves the discrepancy and fixes this issue.
