### ISSUE TITLE
Update surface albedo in TUV-x prior to calculating rate constants

### ISSUE THREAD

**Issue by mattldawson** [ESCOMP/atmospheric_physics#96]
Update the profile of surface albedos in TUV-x for each column prior to calculating photolysis rate constants.

**Acceptance Criteria**
- TUV-x photolysis rate constants are calculated for the actual surface albedos for each column at each timestep

**Ideas**
- Identify the CCPP standard name for surface albedos
- Possible create a stub function for surface albedo if these are not yet calculated in any physics scheme
- Follow the logic of the TUV-x PR into CAM: https://github.com/ESCOMP/CAM/blob/c12d1e46e0fdc1dccb0a651a6c9fefd6bb80b2ba/src/chemistry/mozart/mo_tuvx.F90#L1417-L1436

**Comment by boulderdaze** [comment]
Hi @mattldawson, in musica, `surface albedo` is named as `single_scattering_albedo`. Which one do you think we need to name it for the wrapper in this repository?
